#!/bin/bash

aws ec2 describe-security-groups | jq -r '.SecurityGroups | (["GROUP ID", "GROUP NAME", "DESCRIPTION"], ["-------", "----------", "-----------"], (.[] | [.GroupId, .GroupName, .Description])) | @tsv'
